Repository WildCodeSchool/2023-02-Orleans-Spe-P1-A, pull requests merged in 2023-03, with the labels that each got.

#9 create page prepare your visit
  assets/images/Activities.jpg
  assets/images/Lion_ticket.jpg
  assets/images/Monkey_ticket.jpg
  assets/images/Restaurant.jpg
  assets/images/Tiger.jpg
  assets/images/meerkat_ticket.jpg
  assets/visit.css
  visit.html
Labels: reviewed

#8 Ameliorated header
  assets/images/header-paint.png
  assets/style.css
  components/hero.html
  components/navbar.html
  index.html
Labels: reviewed, conflict solved

#15 Paint effect on header
  assets/contact.css
  assets/images/lion-cub-header.jpg
  assets/style.css
  assets/visit.css
  contact.html
  our-animals.html
  visit.html
Labels: reviewed

#13 Fix responsive contact
  assets/contact.css
  contact.html
Labels: reviewed, conflict solved

#4 Footer
  assets/style.css
  components/footer.html
Labels: reviewed, conflict solved

#17 fix style of page visit
  assets/visit.css
  visit.html
Labels: reviewed, conflict solved

#12 Page de presentation
  .gitignore
  .prettierrc
  assets/animals.css
  assets/contact.css
  assets/images/hero-wild.jpg
  assets/images/zoo_presentation_1.webp
  assets/images/zoo_presentation_2.jpg
  assets/presentation.css
  assets/style.css
  components/hero.html
  presentation.html
Labels: reviewed, conflict solved

#18 Footer on all pages + fix of css code
  assets/style.css
  contact.html
  index.html
  our-animals.html
  visit.html
Labels: reviewed

#19 fix liens nav et css pété
  assets/style.css
  contact.html
  our-animals.html
  presentation.html
  visit.html
Labels: reviewed

#20 fix broken css contact
  assets/contact.css
Labels: reviewed

#23 Suppression chevrons header
  contact.html
  index.html
  our-animals.html
  presentation.html
  visit.html
Labels: reviewed

#21 fix link nav on index
  index.html
Labels: reviewed, conflict solved

#26 Fix presentation page
  assets/presentation.css
  presentation.html
Labels: reviewed, conflict solved

#27 delete style.css
  style.css
Labels: reviewed

#28 fix giraffe picture home
  assets/home.css
Labels: reviewed

#29 modif couleur du burger
  assets/style.css
Labels: reviewed

#30 fix dev to main
  assets/images/hero.jpg
  assets/scripts/cookies.js
Labels: reviewed

#31 footer presentation
  presentation.html
Labels: reviewed

#32 fix color card
  assets/style.css
Labels: reviewed

#34 changed all assets links
  assets/animals.css
  assets/contact.css
  assets/home.css
  assets/presentation.css
  assets/style.css
  assets/visit.css
  contact.html
  index.html
  our-animals.html
  presentation.html
  visit.html
Labels: reviewed

#16 Dev to main
  .gitignore
  .prettierrc
  assets/accueil.css
  assets/animals.css
  assets/contact.css
  assets/home.css
  assets/images/Activities.jpg
  assets/images/Lion_ticket.jpg
  assets/images/Monkey_ticket.jpg
  assets/images/Restaurant.jpg
  assets/images/elephant.svg
  assets/images/giraffe-min.jpg
  assets/images/giraffe.jpg
  assets/images/header-paint.png
  assets/images/hero-wild.jpg
  assets/images/hero.jpg
  assets/images/kangaroo.jpg
  assets/images/koala.jpg
  assets/images/komodo-dragon.jpg
  assets/images/lion-cub-header.jpg
  assets/images/lion.jpg
  assets/images/little_girafe2.png
  assets/images/meerkat_ticket.jpg
  assets/images/quokka.jpg
  assets/images/tiger-header.jpg
  assets/images/tiger-zoo-access.jpg
  assets/images/tiger.jpg
  assets/images/zebra-header.jpg
  assets/images/zebra.jpg
  assets/images/zoo_presentation_1.webp
  assets/images/zoo_presentation_2.jpg
  assets/js/burger.js
  assets/presentation.css
  assets/reset.css
  assets/scripts/cookies.js
  assets/style.css
  assets/visit.css
  components/accueil.html
  components/cookies.html
  components/footer.html
  components/hero.html
  components/navbar.html
  contact.html
  index.html
  our-animals.html
  package-lock.json
  presentation.html
  textes/contact.txt
  visit.html
Labels: reviewed, Changes made
